//! Decks: what you are drilling.
//!
//! A deck is TOML. It is meant to be written by hand as readily as it is
//! generated by an importer, so the format carries nothing a human would not
//! want to type.

use std::fs;
use std::path::Path;

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};

use crate::keys::Combo;

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Deck {
    /// Identifies the deck in the state file. Renaming a deck therefore
    /// resets its progress, which is the honest behaviour: a renamed deck is
    /// usually a different deck.
    pub name: String,

    #[serde(default)]
    pub description: Option<String>,

    #[serde(default, rename = "card")]
    pub cards: Vec<Card>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Card {
    /// The prompt. Also the card's identity in the state file — edit a
    /// description and you start that card over.
    pub description: String,

    /// Every combination that counts as correct. Two entries mean two keys
    /// that genuinely do the same thing, not two things to memorise.
    pub keys: Vec<String>,

    #[serde(default)]
    pub category: Option<String>,
}

impl Deck {
    pub fn load(path: &Path) -> Result<Deck> {
        let text = fs::read_to_string(path)
            .with_context(|| format!("cannot read deck {}", path.display()))?;
        let deck: Deck = toml::from_str(&text)
            .with_context(|| format!("cannot parse deck {}", path.display()))?;
        deck.validate()?;
        Ok(deck)
    }

    pub fn to_toml(&self) -> Result<String> {
        Ok(toml::to_string_pretty(self)?)
    }

    /// Rejects a deck that would fail confusingly mid-session instead: an
    /// unparseable combination is a typo in the deck, and the place to say so
    /// is at load time.
    pub fn validate(&self) -> Result<()> {
        if self.name.trim().is_empty() {
            bail!("deck has no name");
        }
        if self.cards.is_empty() {
            bail!("deck {:?} has no cards", self.name);
        }
        for card in &self.cards {
            if card.keys.is_empty() {
                bail!("card {:?} has no keys", card.description);
            }
            for key in &card.keys {
                key.parse::<Combo>()
                    .with_context(|| format!("card {:?}", card.description))?;
            }
        }
        Ok(())
    }

    pub fn categories(&self) -> Vec<String> {
        let mut seen: Vec<String> = Vec::new();
        for card in &self.cards {
            let category = card.category.clone().unwrap_or_else(|| "Other".into());
            if !seen.contains(&category) {
                seen.push(category);
            }
        }
        seen
    }
}

impl Card {
    pub fn combos(&self) -> Vec<Combo> {
        self.keys.iter().filter_map(|k| k.parse().ok()).collect()
    }

    pub fn accepts(&self, pressed: &Combo) -> bool {
        self.combos().iter().any(|c| c == pressed)
    }

    pub fn category(&self) -> &str {
        self.category.as_deref().unwrap_or("Other")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn deck(toml: &str) -> Result<Deck> {
        let deck: Deck = toml::from_str(toml)?;
        deck.validate()?;
        Ok(deck)
    }

    #[test]
    fn loads_a_deck() {
        let deck = deck(
            r#"
            name = "niri"
            [[card]]
            description = "Focus column left"
            keys = ["meta+h", "meta+left"]
            category = "Navigation"
            "#,
        )
        .unwrap();

        assert_eq!(deck.cards.len(), 1);
        assert_eq!(deck.categories(), vec!["Navigation"]);
    }

    #[test]
    fn any_listed_combination_is_accepted() {
        let deck = deck(
            r#"
            name = "d"
            [[card]]
            description = "Focus column left"
            keys = ["meta+h", "meta+left"]
            "#,
        )
        .unwrap();

        let card = &deck.cards[0];
        assert!(card.accepts(&"meta+h".parse().unwrap()));
        assert!(card.accepts(&"meta+left".parse().unwrap()));
        assert!(!card.accepts(&"meta+j".parse().unwrap()));
    }

    #[test]
    fn a_broken_combination_fails_at_load_not_mid_session() {
        let err = deck(
            r#"
            name = "d"
            [[card]]
            description = "Nonsense"
            keys = ["meta+h+j"]
            "#,
        )
        .unwrap_err();
        assert!(format!("{err:#}").contains("Nonsense"));
    }

    #[test]
    fn an_empty_deck_is_an_error() {
        assert!(deck("name = \"d\"").is_err());
    }
}
